sudo: required
git:
  depth: 1
  submodules_depth: 1

language: cpp

services: docker

os: linux

dist: xenial

compiler:
  - clang
  - gcc

env:
  - NAME="Ubuntu"

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release 

script:
  - git clone https://github.com/Niram7777/nvidia-docker.git
  - cd nvidia-docker
  - make ubuntu-latest
  - cd -
  - docker build -t rpcs3 .
  - sudo apt update
  - sudo apt install binutils-dev build-essential cmake git libcurl4-openssl-dev libdw-dev libiberty-dev python zlib1g-dev
  - git clone https://github.com/SimonKagstrom/kcov.git
  - mkdir -p kcov/build
  - cd kcov/build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j8 ; sudo make install
  - cd -
  - source .dockerrc
  - docker_rpcs3 -u -m -g
  - mkdir coverage
  - /usr/local/bin/kcov --include-pattern=./rpcs3,./Utilities/,./3rdparty/,./Vulkan/ coverage/ ./Docker_Debug_clang/bin/rpcs3
  - bash <(curl -s https://codecov.io/bash) -s coverage/

