sudo: required

git:
  depth: 1
  submodules_depth: 1

cache:
  directories:
    - /home/travis/build/Niram7777/rpcs3/Docker_"$BUILD_TYPE"_"$CC"
    - /home/travis/build/Niram7777/rpcs3/Docker_Debug_clang

cache: ccache

language: cpp

services: docker

os: linux

dist: xenial

compiler:
  - clang
#  - gcc

env:
  - NAME="Ubuntu"

env:
  - BUILD_TYPE=Debug
#  - BUILD_TYPE=Release 

script:
  - ccache -s
  - which -a g++ gcc clang clang++
  - git clone https://github.com/Niram7777/nvidia-docker.git
  - make ubuntu-latest -C nvidia-docker
  - docker build -t rpcs3 .
  - source .dockerrc
  - chmod -R o+rwx "$HOME/.ccache"
  - docker_rpcs3 -u -m -t -c
  - ccache -s
  - bash <(curl -s https://codecov.io/bash) -s coverage/

