sudo: required

git:
  depth: 1
  submodules_depth: 1

language: cpp

services: docker

os: linux

dist: xenial

compiler:
  - clang
#  - gcc

env:
  - NAME="Ubuntu"

env:
  - BUILD_TYPE=Debug
#  - BUILD_TYPE=Release 

cache:
  timeout: 6000
  ccache: true
  directories:
    - Docker_"$BUILD_TYPE"_"$CC"

script:
  - umask 000
  - git clone https://github.com/Niram7777/nvidia-docker.git
  - make ubuntu-latest -C nvidia-docker &> nvidia-docker.log
  - docker build --build-arg U_ID="$(id -u)" --build-arg G_ID="$(id -g)" -t rpcs3 - < Dockerfile &> rpcs3-docker.log
  - sudo chown -R travis:travis $HOME/.ccache
  - ccache -F 0
  - ccache -M 0
  - source .dockerrc
  - docker_rpcs3 -u -m -t -c
  - bash <(curl -s https://codecov.io/bash) -s coverage/

