sudo: required

git:
  depth: 1
  submodules_depth: 1

language: cpp

services: docker

os: linux

dist: xenial

compiler:
  - clang
#  - gcc

env:
  - NAME="Ubuntu"

env:
  - BUILD_TYPE=Debug
#  - BUILD_TYPE=Release 

cache:
  timeout: 6000
  ccache: true
  directories:
    - Docker_"$BUILD_TYPE"_"$CC"
    - rpcs3/Docker_Debug_clang
    - /home/travis/.ccache

script:
  - git clone https://github.com/Niram7777/nvidia-docker.git
  - make ubuntu-latest -C nvidia-docker
  - docker build -t rpcs3 .
  - source .dockerrc
  - ccache -F 0
  - ccache -M 0
  - du -h $HOME/.ccache
  - docker_rpcs3 -u -m -t -c
  - bash <(curl -s https://codecov.io/bash) -s coverage/

