sudo: required

git:
  depth: 1
  submodules_depth: 1

language: cpp

services: docker

os: linux

dist: xenial

compiler:
  - clang
#  - gcc

env:
  - NAME="Ubuntu"

env:
  - BUILD_TYPE=Debug
#  - BUILD_TYPE=Release 

cache:
  timeout: 6000
  ccache: true
  directories:
    - Docker_"$BUILD_TYPE"_"$CC"
    - /home/travis/.ccache

script:
  - git clone https://github.com/Niram7777/nvidia-docker.git
  - make ubuntu-latest -C nvidia-docker &> nvidia-docker.log
  - docker build -t rpcs3 . &> rpcs3-docker.log
  - source .dockerrc
  - sudo chmod -R 777 Docker_"$BUILD_TYPE"_"$CC"
  - sudo chmod -R 777 /home/travis/.ccache
  - docker_rpcs3 -u -m -t -c
  - bash <(curl -s https://codecov.io/bash) -s coverage/

