sudo: required

language: cpp

services: docker

os: linux

dist: xenial

compiler:
  - clang
  - gcc

matrix:
  include:
  - name: "Ubuntu Clang Debug"
    env:
      - NAME="Ubuntu"
      - BUILD_TYPE=Debug 
  - name: "Ubuntu $CC Release"
    env:
      - NAME="Ubuntu"
      - BUILD_TYPE=Release 
      - DEPLOY_APPIMAGE="true"

before_install:
  - git clone https://github.com/Niram7777/nvidia-docker.git ; cd nvidia-docker ; make ubuntu-latest ; cd -
  - docker build -t rpcs3 .
  - git clone https://github.com/SimonKagstrom/kcov.git ; mkdir -p kcov/build ; cd kcov/build ; cmake -DCMAKE_BUILD_TYPE=Release .. ; make -j8 ; cd - 
script:
  - source .dockerrc
  - docker_rpcs3 -m -g
  - mkdir coverage
  - ./kcov/build/kcov --include-pattern=./rpcs3,./Utilities/,./3rdparty/,./Vulkan/ coverage/ ./Docker_Debug_clang/bin/rpcs3
  - bash <(curl -s https://codecov.io/bash) -s coverage/

