version: 2.1

#orbs:
#  codecov: codecov/codecov@1.0.4

jobs:
  build:
    working_directory: ~/
    machine:
      image: ubuntu-1604:201903-01
    environment:
      NAME: Ubuntu
      BUILD_TYPE: Debug
      CC: clang
      CXX: clang++
    steps:
      - run:
          name: Set Cache Env var
          command: |
            pyenv global 3.7.0
            PREVIOUS_COMMIT=$(curl -s "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/commits/$CIRCLE_BRANCH" | python3 -c "import sys, json; print(json.load(sys.stdin)['parents'][0]['sha'])")
            echo $PREVIOUS_COMMIT
            echo "export PREVIOUS_COMMIT=$PREVIOUS_COMMIT" >> $BASH_ENV
      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-{{ .Environment.PREVIOUS_COMMIT }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      - run:
          name: Clone
          command: |
            echo $PREVIOUS_COMMIT
            if [ ! -d rpcs3 ];
            then
                git clone -j $(nproc) --recurse-submodules --depth=1 --branch=$CIRCLE_BRANCH https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git rpcs3
            else
                git -C rpcs3 reset --hard
                git -C rpcs3 submodule foreach --recursive git reset --hard
                git -C rpcs3 submodule update --init --recursive
                git -C rpcs3 pull --recurse-submodules
            fi
      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/rpcs3/.git"
            - "~/rpcs3/*/.git"
            - "~/rpcs3/**/*/.git"

      - restore_cache:
          keys:
            - build-v3-{{ .Environment.NAME }}-{{ .Environment.CC }}-{{ .Environment.BUILD_TYPE }}-{{ .Revision }}
            - build-v3-{{ .Environment.NAME }}-{{ .Environment.CC }}-{{ .Environment.BUILD_TYPE }}-{{ .Environment.PREVIOUS_COMMIT }}
            - build-v3-
      - run:
          name: Build and test
          command: |
            cd ~/rpcs3
            find $PWD -name pause.png
            bash ~/rpcs3/.circleci/build_test.sh
      - save_cache:
          key: build-v3-{{ .Environment.NAME }}-{{ .Environment.CC }}-{{ .Environment.BUILD_TYPE }}-{{ .Revision }}
          paths:
              - ~/rpcs3/Docker_"$BUILD_TYPE"_"$CC"
              - ~/.ccache

      - store_artifacts:
          path: ~/rpcs3/Docker_"$BUILD_TYPE"_"$CC"
      - store_test_results:
          path: ~/rpcs3/coverage

