version: 2.1

#orbs:
#  codecov: codecov/codecov@1.0.4

jobs:
  build:
    working_directory: ~/
    machine:
      image: ubuntu-1604:201903-01
    environment:
      NAME: Ubuntu
      BUILD_TYPE: Debug
      CC: clang
      CXX: clang++
    steps:
      - run: sudo apt update && sudo apt install -y git make bash
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - run:
          name: Clone
          command: |
            if [ ! -d rpcs3 ];
            then
                git clone -j $(nproc) --recurse-submodules --depth=1 --branch=$CIRCLE_BRANCH https://github.com/Niram7777/rpcs3.git rpcs3
            else
                git -C rpcs3 pull --recurse-submodules
                git -C rpcs3 submodule update --init --recursive
                git -C rpcs3 reset --hard
            fi
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/rpcs3/.git"
            - "~/rpcs3/*/.git"
            - "~/rpcs3/**/*/.git"

      - restore_cache:
          keys: build-v1-{{ .Environment.NAME }}-{{ .Environment.CC }}-{{ .Environment.BUILD_TYPE }}
      - run:
          name: Build and test
          command: |
            cd ~/rpcs3
            bash ~/rpcs3/.circleci/build_test.sh
      - save_cache:
          key: build-v1-{{ .Environment.NAME }}-{{ .Environment.CC }}-{{ .Environment.BUILD_TYPE }}
          paths:
              - ~/rpcs3/Docker_\"$BUILD_TYPE\"_\"$CC\"
              - ~/.ccache

      - store_artifacts:
          path: Docker_"$BUILD_TYPE"_"$CC"
      - store_test_results:
          path: coverage

