version: 2.1

#orbs:
#  codecov: codecov/codecov@1.0.4

jobs:
  build:
    working_directory: ~/
    docker:
      - image: docker
    environment:
      NAME: Ubuntu
      BUILD_TYPE: Debug
      CC: clang
      CXX: clang++
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Creating Dummy Artifacts
          command: ./build_test.sh
      - store_artifacts:
          path: Docker_"$BUILD_TYPE"_"$CC"
      - store_test_results:
          path: coverage

