version: 2.1

#orbs:
#  codecov: codecov/codecov@1.0.4

jobs:
  build:
    working_directory: ~/
    docker:
      - image: ubuntu:rolling
    environment:
      NAME: Ubuntu
      BUILD_TYPE: Debug
      CC: clang
      CXX: clang++
    steps:
      - run: apt update && apt install -y git make
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - run:
          name: Clone
          command: |
            git clone -j $(nproc) --recurse-submodules --depth=1 --branch=$CIRCLE_BRANCH https://github.com/Niram7777/rpcs3.git rpcs3
            git pull --recurse-submodules --depth=1
#            git -C rpcs3 submodule update --init --recursive --depth=1
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/rpcs3/.git"
            - "~/rpcs3/*/.git"
            - "~/rpcs3/**/*/.git"
      - restore_cache:
          keys: cache-id_{{ .Environment.NAME }}-{{ .Environment.CC }}-{{ .Environment.BUILD_TYPE }}
      - run:
          name: Build and test
          command: |
            cd ~/rpcs3
            ~/rpcs3/.circleci/build_test.sh
      - save_cache:
          key: cache-id_{{ .Environment.NAME }}-{{ .Environment.CC }}-{{ .Environment.BUILD_TYPE }}
          paths:
              - ~/rpcs3/Docker_\"$BUILD_TYPE\"_\"$CC\"
              - ~/.ccache

      - store_artifacts:
          path: Docker_"$BUILD_TYPE"_"$CC"
      - store_test_results:
          path: coverage

